[project]
name = "mcp-prac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.14.3",
    "pydantic>=2.12.5",
    "rich>=14.2.0",
    "sqlalchemy>=2.0.46",
]
